spring:
  mvc:
    view:
      suffix: .html
  h2:
    console:
      enabled: true
      path: /h2_db
  datasource:
    url: jdbc:h2:mem:test;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  thymeleaf:
    prefix : classpath:templates/
    suffix: .html
    cache: false